### ISSUE TITLE
Tips for Unwinding with UINavigationController?

### ISSUE THREAD

**Issue by maksutovic** [Phillipus/CustomSegue#1]
This is excellent, and very helpful. However, I am using a navigation controller and having some issues. I have subclassed my navigation controller and added the 
`- (UIStoryboardSegue *)segueForUnwindingToViewController:(UIViewController *)toViewController fromViewController:(UIViewController *)fromViewController identifier:(NSString *)identifier` method per Apple docs, however I am confused in how to properly dismiss the source controller and present the destination controller. Any tips would be great.

**Comment by Phillipus** [comment]
Hi, are you sure you need to use this with a navigation controller? I'm wondering if users might expect the typical behaviour to go back to the previous view?

**Comment by monizj** [comment]
Hi,  I am trying to zoom out to Landscape and it seems to always zoom from Portrait.  Is there anything I can do to force landscape?
