### ISSUE TITLE
Incompatible with iOS8.0

### ISSUE THREAD

**Issue by nightfall708** [Phillipus/CustomSegue#2]
It seems this doesn't work well with iOS 8.0:

```
2014-09-02 15:03:30.054 CustomSegue[1963:605904] Unbalanced calls to begin/end appearance transitions for <SecondViewController: 0x16d8ba40>.
```

**Comment by Phillipus** [comment]
iOS 7 is only supported for this. iOS 8 will probably make this redundant.

**Comment by nightfall708** [comment]
How so? so how custom segues will work there?

**Comment by marcphk** [comment]
I'm finding the same. Is there any way to solve this for iOS 8? Edit: I note that not removing the temp view from the super view works.
